apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-lab.fullname" . }}-redis-config
  labels:
    {{- include "k8s-lab.labels" . | nindent 4 }}
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    bind 0.0.0.0
    protected-mode no
    maxmemory-policy noeviction