apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-lab.fullname" . }}-redis-auth
  labels:
    {{- include "k8s-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}